default_stages:
  - "pre-commit"
repos:
  - repo: https://github.com/trufflesecurity/trufflehog
    rev: v3.87.2
    hooks:
      - id: trufflehog
        entry: trufflehog git file://. --since-commit HEAD --fail
