[tools]
bat = "0.26"
delta = "0.19"
fd = "10"
ffmpeg = "8"
fzf = "0.71"
gh = "2"
glow = "2"
gum = "0.17"
jq = "1"
lazydocker = "0.25"
lazygit = "0.61"
lua = "5.1"
neovim = "0.11"
node = "25"
opencode = "latest"
pre-commit = "4"
python = "3.14"
resvg = "0.47"
ripgrep = "15"
shellcheck = "0.11"
stylua = "2"
tlrc = "1"
tree-sitter = "0.26"
trufflehog = "3"
uv = "0.11"
vhs = "0.11"
yazi = "26"
zoxide = "0.9"
