#Config docs: https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md
gui:
  scrollHeight: 10
  mouseEvents: false
  expandFocusedSidePanel: true
  showCommandLog: true
  nerdFontsVersion: "3"
  theme:
    # Catppuccin macchiato
    activeBorderColor:
      - '#a6da95'
      - bold
    inactiveBorderColor:
      - '#a5adcb'
    optionsTextColor:
      - '#8aadf4'
    selectedLineBgColor:
      - '#363a4f'
    cherryPickedCommitBgColor:
      - '#494d64'
    cherryPickedCommitFgColor:
      - '#a6da95'
    unstagedChangesColor:
      - '#ed8796'
    defaultFgColor:
      - '#cad3f5'
    searchingActiveBorderColor:
      - '#eed49f'
  # authorColors:
  #   '*': '#b7bdf8'
  branchColors:
    'release': '#ee99a0'
    'main': '#c6a0f6'
git:
  paging:
    pager: "delta --paging=never"
  log:
    showWholeGraph: false
  # 'cr' - relative date
  # 'ci' - iso date
  # 'cs' - short date (YYYY-MM-DD)
  # 'ch' - human readable
  branchLogCmd: "git log --graph --color=always --pretty=format:'%C(cyan)%h%Creset %Cgreen%ch%Creset -%C(yellow)%d%Creset %s %C(red)<%an>%Creset' --abbrev-commit {{branchName}} --"
notARepository: skip
customCommands:
  - key: 'W'
    context: 'files'
    description: 'Amend last commit without pre-commit hook'
    command: "git commit --amend --no-edit --allow-empty --no-verify"
    prompts:
      - type: 'confirm'
        title: 'Amend last commit without pre-commit'
        body: 'Are you sure you want to amend last commit without pre-commit hooks? Afterwards, you can change the commit message from the commits panel.'
