# https://github.com/jesseduffield/lazydocker/blob/master/docs/Config.md
gui:
  scrollHeight: 10
  ignoreMouseEvents: true
  expandFocusedSidePanel: true
  theme:
    # Catppuccin macchiato
    activeBorderColor:
      - '#a6da95'
      - bold
    inactiveBorderColor:
      - '#a5adcb'
    optionsTextColor:
      - '#8aadf4'
    selectedLineBgColor:
      - '#363a4f'
